language: python
os: linux
dis: xenial
python:
- '3.7'

stages:
  - build
  - validate
  - name: deploy
    if: branch = master
  - name: post-deploy
    if: branch = master

before_script:
  - git clone https://github.com/AWegnerGithub/awegnergithub.github.io-source.git source
  - mkdir source/content
  - rsync -av --progress ./* source/content --exclude source
  - cd source
  - pip install --upgrade pip
  - pip install -r requirements.txt

jobs:
  include:
    - stage: build
      script: bash scripts/build.sh
    - stage: validate
      script: bash scripts/validate.sh
    - stage: deploy
      script: bash scripts/deploy.sh
    - script: post-deploy
      script: bash scripts/post-deploy.sh

notifications:
  email:
    on_success: always
    on_failure: always
