language: python
os: linux
dis: xenial
python:
- '3.7'

stages:
  - checkout
  - build
  - validate
  - name: deploy
    if: branch = master
  - name: post-deploy
    if: branch = master

jobs:
  include:
    - stage: checkout
      script: bash scripts/checkout.sh
    - stage: build
      script: bash scripts/build.sh
    - stage: validate
      script: bash scripts/validate.sh
    - stage: deploy
      script: bash scripts/deploy.sh
    - script: post-deploy
      script: bash scripts/post-deploy.sh

notifications:
  email:
    on_success: always
    on_failure: always
