name: "IndexNow"
on:
  schedule:
  - cron:  '0 4,16 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: indexnow-action
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: "https://bojieyang.github.io/sitemap.xml"
          since: 1
          since-unit: "day"
          key: ${{ secrets.INDEXNOW_KEY }}